version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data # Persistencia de datos

  nodejs:
    image: node:latest
    container_name: node_container
    working_dir: /app
    command: node server.js
    ports:
      - "3000:3000" 
    volumes:
      - ./node-app:/app 
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data: 
  redis_data: 
